fail_fast: false # using true is too annoying in development

repos:
  # run pre-commit autoupdate to update these versions
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files # prevents giant files from being committed.
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-yaml # checks yaml files for parseable syntax.
        args: [--allow-multiple-documents]
      - id: detect-private-key # detects the presence of private keys.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: fix-byte-order-marker # removes utf-8 byte order marker.
      - id: mixed-line-ending # replaces or checks mixed line ending.
      - id: trailing-whitespace # trims trailing whitespace.
      - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang.
      - id: check-shebang-scripts-are-executable # ensures that (non-binary) files with a shebang are executable.
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: forbid-submodules

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

#  activate when csorchestrator is available as a package and can be added as additional-dependencies, for now, use as local command
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.20.2
#    hooks:
#      - id: mypy
#        args:
#          [
#            "--config-file=pyproject.toml",
#          ]
#        additional_dependencies:
#          - types-PyYAML
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: python -m mypy .
        language: system
        pass_filenames: false
        args:
          - --config-file=pyproject.toml

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint

  - repo: local
    hooks:
      - id: no-unstaged-changes
        name: Fail if unstaged changes exist
        entry: git diff --quiet
        language: system
        pass_filenames: false
